[tool.tbump]

[[tool.tbump.file]]
src = "package.json"

[[tool.tbump.file]]
src = "README.md"

[tool.tbump.version]
current = "0.1.3"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[tool.tbump.git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"
