name: Upload Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build 
        id: build
        run: |
          npm install -g @vscode/vsce
          npm install
          vsce package --no-rewrite-relative-links
          now=`date +"%Y-%m-%d__%H:%M"`
          file=`ls *.vsix`
          file_ver="${now}_${file}"
          mv $file $file_ver
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: latest
          files: |
            *.vsix
